import { BibleBook } from '@/types/Filter';

export const BOOK_ICONS_PATH = '/icons/bible-books';

export const BIBLE_BOOKS: BibleBook[] = [
  { book: 'genesis', name: 'Genesi', icon: 'genesis.svg' },
  { book: 'exodus', name: 'Esodo', icon: 'exodus.svg' },
  { book: 'leviticus', name: 'Levitico', icon: 'leviticus.svg' },
  { book: 'numbers', name: 'Numeri', icon: 'numbers.svg' },
  { book: 'deuteronomy', name: 'Deuteronomio', icon: 'deuteronomy.svg' },
  { book: 'joshua', name: 'Giosuè', icon: 'joshua.svg' },
  { book: 'judges', name: 'Giudici', icon: 'judges.svg' },
  { book: 'ruth', name: 'Ruth', icon: 'ruth.svg' },
  { book: '1samuel', name: '1 Samuele', icon: '1-samuel.svg' },
  { book: '2samuel', name: '2 Samuele', icon: '2-samuel.svg' },
  { book: '1kings', name: '1 Re', icon: '1-kings.svg' },
  { book: '2kings', name: '2 Re', icon: '2-kings.svg' },
  { book: '1chronicles', name: '1 Cronache', icon: '1-chronicles.svg' },
  { book: '2chronicles', name: '2 Cronache', icon: '2-chronicles.svg' },
  { book: 'ezra', name: 'Esdra', icon: 'ezra.svg' },
  { book: 'nehemiah', name: 'Neemia', icon: 'nehemiah.svg' },
  { book: 'esther', name: 'Ester', icon: 'esther.svg' },
  { book: 'job', name: 'Giobbe', icon: 'job.svg' },
  { book: 'psalms', name: 'Salmi', icon: 'psalms.svg' },
  { book: 'proverbs', name: 'Proverbi', icon: 'proverbs.svg' },
  { book: 'ecclesiastes', name: 'Ecclesiaste', icon: 'ecclesiastes.svg' },
  {
    book: 'songofsolomon',
    name: 'Canto dei Cantici',
    icon: 'song-of-songs.svg',
  },
  { book: 'isaiah', name: 'Isaia', icon: 'isaiah.svg' },
  { book: 'jeremiah', name: 'Geremia', icon: 'jeremiah.svg' },
  { book: 'lamentations', name: 'Lamentazioni', icon: 'lamentations.svg' },
  { book: 'ezekiel', name: 'Ezechiele', icon: 'ezekiel.svg' },
  { book: 'daniel', name: 'Daniele', icon: 'daniel.svg' },
  { book: 'hosea', name: 'Osea', icon: 'hosea.svg' },
  { book: 'joel', name: 'Gioele', icon: 'joel.svg' },
  { book: 'amos', name: 'Amos', icon: 'amos.svg' },
  { book: 'obadiah', name: 'Abdia', icon: 'obadiah.svg' },
  { book: 'jonah', name: 'Giona', icon: 'jonah.svg' },
  { book: 'micah', name: 'Michea', icon: 'micah.svg' },
  { book: 'nahum', name: 'Nahum', icon: 'nahum.svg' },
  { book: 'habakkuk', name: 'Abacuc', icon: 'habakkuk.svg' },
  { book: 'zephaniah', name: 'Sofonia', icon: 'zephaniah.svg' },
  { book: 'haggai', name: 'Aggeo', icon: 'haggai.svg' },
  { book: 'zechariah', name: 'Zaccaria', icon: 'zechariah.svg' },
  { book: 'malachi', name: 'Malachia', icon: 'malachi.svg' },
  { book: 'matthew', name: 'Matteo', icon: 'matthew.svg' },
  { book: 'mark', name: 'Marco', icon: 'mark.svg' },
  { book: 'luke', name: 'Luca', icon: 'luke.svg' },
  { book: 'john', name: 'Giovanni', icon: 'john.svg' },
  { book: 'acts', name: 'Atti', icon: 'acts.svg' },
  { book: 'romans', name: 'Romani', icon: 'romans.svg' },
  { book: '1corinthians', name: '1 Corinzi', icon: '1-corinthians.svg' },
  { book: '2corinthians', name: '2 Corinzi', icon: '2-corinthians.svg' },
  { book: 'galatians', name: 'Galati', icon: 'galatians.svg' },
  { book: 'ephesians', name: 'Efesini', icon: 'ephesians.svg' },
  { book: 'philippians', name: 'Filippesi', icon: 'philippians.svg' },
  { book: 'colossians', name: 'Colossesi', icon: 'colossians.svg' },
  {
    book: '1thessalonians',
    name: '1 Tessalonicesi',
    icon: '1-thessalonians.svg',
  },
  {
    book: '2thessalonians',
    name: '2 Tessalonicesi',
    icon: '2-thessalonians.svg',
  },
  { book: '1timothy', name: '1 Timoteo', icon: '1-timothy.svg' },
  { book: '2timothy', name: '2 Timoteo', icon: '2-timothy.svg' },
  { book: 'titus', name: 'Tito', icon: 'titus.svg' },
  { book: 'philemon', name: 'Filemone', icon: 'philemon.svg' },
  { book: 'hebrews', name: 'Ebrei', icon: 'hebrews.svg' },
  { book: 'james', name: 'Giacomo', icon: 'james.svg' },
  { book: '1peter', name: '1 Pietro', icon: '1-peter.svg' },
  { book: '2peter', name: '2 Pietro', icon: '2-peter.svg' },
  { book: '1john', name: '1 Giovanni', icon: '1-john.svg' },
  { book: '2john', name: '2 Giovanni', icon: '2-john.svg' },
  { book: '3john', name: '3 Giovanni', icon: '3-john.svg' },
  { book: 'jude', name: 'Giuda', icon: 'jude.svg' },
  { book: 'revelation', name: 'Apocalisse', icon: 'revelation.svg' },
];
