import { DoctrinalItem } from './types';

export const DoctrinalItems: DoctrinalItem[] = [
  {
    id: 1,
    title: 'Dio:',
    text: "Crediamo che vi è un solo e vero Dio e che Egli sussiste in tre persone: Padre, Figlio e Spirito Santo; Egli è l'autore della creazione, della provvidenza, della redenzione e del giudizio. Egli è Eterno, Infinito, Onnipresente, Onnipotente e Sovrano. Egli è l'unico degno di ricevere l'adorazione e la lode.",
    verses: [
      'Genesi 1:1-2',
      'Deuteronomio 6:4',
      'Matteo 28:19',
      'Atti 17:28',
      'Apocalisse 4:11',
    ],
  },
  {
    id: 2,
    title: 'Le Sacre Scritture:',
    text: "Crediamo che la Bibbia è interamente Parola di Dio. Essa si compone di 66 libri, suddivisi nell'Antico e nel Nuovo Testamento. Crediamo che la Scrittura sia Divinamente Ispirata e quindi: inerrante; infallibile, autorevole, chiara, sufficiente, immutabile, invincibile, vincolante e completa. Tutto ciò comporta non solo che non necessita dell'aggiunta di testi, dogmi e/o rivelazioni da parte di profeti, magisteri ecclesiastici o perfino angeli; ma ne vieta la presenza mediante la sua stessa ed insita autorità. Essa è la suprema autorità in ogni materia di fede e di condotta.",
    verses: [
      '1 Corinzi 4:6',
      '2 Timoteo 3:16-17',
      'Ebrei 1:1-2',
      '2 Pietro 1:19-21',
      'Giuda 3',
      'Apocalisse 22:18-19',
    ],
  },
  {
    id: 3,
    title: "L'uomo e la caduta:",
    text: "Crediamo che l'essere umano è stato creato ad immagine di Dio; tuttavia, avendo disubbidito, è caduto in uno stato di perdizione; pertanto ogni aspetto della sua vita è totalmente corrotto dal peccato. Egli vive sotto il dominio di Satana, in rivolta contro Dio e nell'assoluta incapacità di potersi liberare, redimere, riscattare o anche solo volgersi verso Gesù Cristo.",
    verses: [
      'Genesi 1:27; 3:16-19',
      'Isaia 64:6',
      'Romani 3:9-23',
      'Efesini 2:2-3',
    ],
  },
  {
    id: 4,
    title: "L'opera della salvezza:",
    text: "Crediamo che il Signore, Uno e Trino, è intervenuto per la salvezza degli uomini peccatori; il Padre prima della creazione del mondo, per la Sua grazia Sovrana, ha eletto un gran numero di gente dalla massa decaduta dell'umanità; senza favoritismi ha eletto gente da ogni lingua, tribù, popolo e nazione; tale decisione non è avvenuta per una sua previsione dei fatti futuri ma per il suo consiglio eterno ed immutabile. Gesù Cristo, Il Figlio mandato dal Padre, la Parola fatta carne, è nato senza peccato dalla Vergine Maria. Egli, vero Dio e vero Uomo, dopo aver vissuto una vita perfetta in obbedienza al Padre, è morto sulla croce al posto del suo popolo. Attraverso tale morte sostitutiva ed espiatrice, si riceve il perdono dei peccati e si è liberati dal giudizio e la condanna. Egli è risorto corporalmente dai morti, è asceso al cielo e siede alla destra del Padre come unico mediatore tra Dio e gli uomini. Alla fine dei tempi ritornerà per giudicare i vivi e i morti. Lo Spirito Santo chiama efficacemente gli eletti. Applica loro la salvezza fin dall'inizio, producendo la nuova nascita. Conduce lungo il percorso di santificazione e produce i suoi frutti, tra i quali la perseveranza stessa fino alla fine.",
    verses: [
      'Efesini 1:3-14',
      'Romani 9:14-24',
      'Giovanni 1:1-18',
      'Matteo 1:18-25',
      'Luca 2:1-20',
      'Galati 3:13',
      'Apocalisse 5:9-10',
      'Giovanni 10:11',
      'Efesini 5:25-27',
      '1 Timoteo 2:5-6',
      '2 Tessalonicesi 2:13',
      '1 Pietro 1:2',
      'Giovanni 3:5-8; 16:8',
      'Romani 8:1-17',
      '1 Corinzi 2:12-16',
    ],
  },
  {
    id: 5,
    title: 'La vita cristiana:',
    text: "Crediamo che il cristiano è giustificato per grazia di Dio mediante la fede in Cristo Gesù. Attraverso la stessa fede è unito a Cristo e questa unione comporta non solo l'essere giustificati, ma anche l'essere rigenerati e santificati. Tutte queste cose sono ricevute da ogni vero credente e costituiscono la salvezza ricevuta da Dio; le buone opere non sono, quindi, la causa della salvezza, ma il frutto e l'evidenza della giustificazione e salvezza ricevute. Così, per sola grazia di Dio, il credente è santificato e custodito da Dio fino alla fine.",
    verses: [
      'Romani 5:1-9',
      'Tito 3:4-7',
      'Romani 6:1-23; 8:28-39',
      'Filippesi 1:6',
      'Giacomo 2:14-26',
      'Giuda 24-25',
    ],
  },
  {
    id: 6,
    title: 'La Chiesa:',
    text: "Crediamo che la chiesa è costituita da tutti coloro che sono veramente credenti il cui Capo è Gesù Cristo. Essa, oltre ad avere una dimensione universale o generale, si manifesta nella sua dimensione locale. La sua missione è quella di adorare, lodare, servire Dio, evangelizzare il mondo e qualora sia necessario esercitare la disciplina correttiva allo scopo di mantenere la sua purezza secondo l'insegnamento delle Scritture. Al fine di edificare la chiesa locale, lo Spirito Santo dona ai suoi membri dei doni; inoltre nella chiesa alcuni sono appartati per ricoprire il ruolo di anziani e diaconi e la Chiesa è chiamata a riconoscerli e ordinarli secondo l'insegamento delle Scritture.",
    verses: [
      'Matteo 16:16-18; 18:15-18; 28:19-20',
      'Atti 6:1-6; 13:1-3; 14:23',
      '1 Corinzi 1:2; 5:1-11; 12:1-31',
      'Romani 12:4-21',
      'Galati 6:1',
      'Efesini 4:11-16',
      'Filippesi 1:1',
      '1 Timoteo 1:20; 3:1-13; 5:17-22',
      'Tito 1:5-9; 3:9-11',
      'Ebrei 12:1-14',
    ],
  },
  {
    id: 7,
    title: 'Sacramenti / Ordinanze:',
    text: "Crediamo che le uniche ordinanze istituite da Cristo per la Chiesa neo-testamentaria sono il Battesimo e la Cena del Signore. Crediamo che il Battesimo debba essere ministrato per immersione a tutti coloro che hanno fatto professione di fede e che non mostrano ragionevoli dubbi riguardo alla loro rigenerazione; crediamo che il battesimo sia un atto di testimonianza della propria fede, dell'identificazione con Cristo, dell'opera dello Spirito Santo ricevuta e di impegno a seguire il Signore ed ubbidirgli sempre. Crediamo che la Cena del Signore è fondata sulla comunione ed esprime il ricordo dell'opera di Cristo, l'obbedienza e la speranza di coloro che sono stati salvati. La Chiesa è chiamata ad osservare correttamente entrambi i sacramenti affinchè possa godere della grazia divina attraverso di loro, non per una efficacia insita nei sacramenti stessi o della persona che li amministra, ma mediante lo Spirito Santo ed in forza della fede di colui che vi partecipa.",
    verses: [
      'Matteo 28:19',
      'Atti 2:41-42; 8:36-38',
      'Romani 6:1-6',
      '1 Corinzi 12:12-13',
      'Colossesi 1:21',
      '1 Pietro 3:18-21',
      '1 Corinzi 10:16-17; 11:26-29',
    ],
  },
  {
    id: 8,
    title: 'Il governo civile:',
    text: "Crediamo che il governo civile sia ordinato da Dio al fine di perseguire il benessere della società umana, mantenere l'ordine sociale, promuovere il bene e punire il male. E' dovere di ogni cristiano pregare per i governanti, rispettarli, obbedirgli. Tuttavia, il cristiano è dispensato dalla cieca obbedienza e può disubbidire alle autorità ed alla legge civile qualora mai questi dovessero imporre o vietare comportamenti che lo porrebbero in contrasto e/o ribellione con le Scritture. Infatti il cristiano ha come priorità assoluta Dio e l'obbedienza a Lui.",
    verses: [
      'Daniele 3:1-30; 6:1-28',
      'Matteo 22:15-23',
      'Romani 13:1-7',
      '1 Timoteo 2:1-4',
      'Tito 3:1',
    ],
  },
  {
    id: 9,
    title: 'Il ritorno di Cristo:',
    text: "Crediamo che Gesù ritornerà dal Cielo, in un giorno e momento a noi sconosciuti, ma stabiliti da Dio; crediamo che prima resusciteranno i morti; poi, i credenti ancora in vita, saranno trasformati. Crediamo che gli increduli saranno giudicati con giustizia da Gesù Cristo stesso e destinati alla punizione eterna dell'inferno, mentre ogni credente gioirà e vivrà eternamente in comunione con Dio nella nuova creazione.",
    verses: [
      'Matteo 24:42-44; 25:31-32',
      'Giovanni 5:28-29',
      'Atti 17:31',
      '1 Corinzi 15:51-57',
      '1 Tessalonicesi 4:13-18',
      '2 Tessalonicesi 1:9',
      '2 Pietro 3:10-13',
      'Apocalisse 21:1-22:16',
    ],
  },
];
